### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xaph1k** [DiscworldZA/gta-resources#112]
when i go to the shop, nothing displays and the name of the menu is a glovebox, when i try to inport the sql file i get this error: https://imgur.com/a/5yArKyG

**Comment by KungRaseri** [comment]
The SQL error is due to your database user not having permission to insert on that table.  Make sure your database user has the right permissions:
`GRANT INSERT ON essentialmode.* TO '[db-user]'@'localhost'` Gives [db-user] INSERT privileges on all tables in essentialmode.
or
`GRANT ALL PRIVILEGES ON essentialmode.* TO '[db-user]'@'localhost'` Gives [db-user] all privileges on the all tables in essentialmode.

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
