### ISSUE TITLE
[BUG] disc-inventoryhud

### ISSUE THREAD

**Issue by Pramudhyta** [DiscworldZA/gta-resources#194]
if other player give item with +1 from maximum number of item, and then i have the wrong stack number of item. 

example : player[2] give me cocacola 90 where i have cocacola 11 in my inventory. and then i have 100 +90 cocacola in my inventory. thats a wrong calculation, i should have a 100+1 cocacola.

**sorry for my bad english** you got it?

**Comment by lGodHatesMel** [comment]
So I u have 100 in 1 stack and 1 in another? @Pramudhyta

**Comment by lGodHatesMel** [comment]
If that is right then I believe it may be because of the new weight system with esx. As with the 'limit' it sets the limit to how many u can have in your "Total Inventory"  but since it's using weight and disc-inventory is really built for that yet it's is not setting a limit in the inventory at all @Pramudhyta

**Comment by Dazedgenie** [comment]
Unfortunately this mod has been deprecated in favour of an entire redesign. NO SUPPORT WILL BE GIVEN FOR THIS VERSION OF DISC-INVENTORYHUD GOING FORWARD, This resource is TOO resource intensive and WILL kill your server if used in production.

All current InventoryHUD features will be carried over to the new inventory redesign which can be found at [https://github.com/DiscworldZA/disc-inventoryhud](url) . This is currently a BETA resource and should be treated as such.
