### ISSUE TITLE
Society Stock Menu Addition [Feature]

### ISSUE THREAD

**Issue by JiminyKroket** [DiscworldZA/gta-resources#293]
I have not messed with the code myself, and I could imagine there would be someone that knows enough it would be a simple conversion for them. It would be a nice addition to have the stocks menu in jobs use disc inventory

**Comment by iTzCrutchie** [comment]
Wouldn't the easiest way would be to just use the stashes feature? Then just remove the stock option from the jobs menu and use the new marker for the inventory since it allows to set specific jobs to open up those stashes.

Otherwise yea it could probably be done but each job script will need to be edited to do to it.

**Comment by JiminyKroket** [comment]
Oh yeah I actually went through it with someone. I forgot i posted this,
I'll close it when I get home today
